language: ruby
rvm:
- ruby 2.4.1

script:
- bundle exec jekyll build
- bundle exec htmlproofer ./_site
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: true # route your build to the container-based infrastructure for a faster build
