# Site settings
title: RMachin
email: rmachin75@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Full-stack Web Developer
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://remachin.herokuapp.com/" # the base hostname & protocol for your site



# Social media profiles - feel free to add more here
twitter_username: raphaelmachin
github_username:  rmachin
#facebook_username: StartBootstrap
#instagram_username: beyonce
#stackoverflow_url: https://
#googleplus_username: BobMarley
#skype_username: echo123
linkedin_url: https://www.linkedin.com/in/remachin/

# Address information
address_street: I Live in
address_city: Miami
address_state: FL
address_zip: 33143

# Build settings
markdown: kramdown
permalink: pretty
exclude: ["Procfile","Gemfile", "Gemfile.lock","config.ru","node_modules", "gulpfile.js", "package.json", "vendor"]
