# Site settings
title: Raphael Machin | Full-stack Web Developer
email: rmachin75@gmail.com
description: Full-stack Web Developer
#baseurl: "" # the subpath of your site, e.g. /blog
url: "http://rmachin-web.s3-website.us-east-2.amazonaws.com/"



# Social media profiles - feel free to add more here
twitter_username: remachin75
github_username:  rmachin
#facebook_username: StartBootstrap
#instagram_username: beyonce
#stackoverflow_url: https://
#googleplus_username: BobMarley
#skype_username: echo123
linkedin_url: https://www.linkedin.com/in/remachin/

# jekyll-assets gem
assets:
  debug: false
  js_compressor:  uglifier
  css_compressor: sass
  sources:
    - assets/css
    - assets/img/portfolio
    - assets/img
    - assets/js
    - _vendors/js
  autoprefixer:
    browsers: ["last 2 versions","> 5%","IE 9"]
  # features:
  #   liquid: true | false | default: false
  #   integrity: true | false | default: false
    # This will add height and width attributes for an img tag.
    # automatic_img_size: true | false | n(fixnum): 2,4,6,8 | default: true
    # This will add the digest path as an alt attribute for an img tag.
    # automatic_img_alt : true | false | default: true

# Address information
address_street: I Live in
address_city: Miami
address_state: FL
address_zip: 33143

# Build settings
markdown: kramdown
permalink: pretty

plugins:
  - jekyll-assets
  - jekyll-sitemap
#==============================
# File inclusions/exclusions
#==============================
exclude: ["s3_website.yml","Procfile","Gemfile", "Gemfile.lock","config.ru","node_modules", "gulpfile.js", "package.json", "vendor"]
